apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-green
  template:
    metadata:
      labels:
        app: aceest-green
    spec:
      containers:
      - name: aceest-container
        image: 2024tm93614/aceest-devops-app:green-v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000